name: Test and Deploy the app

on: 
  workflow_dispatch:
  push: 
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:

      - name: "Print the key"
        run:  |
          echo "DART_VERSION: $DART_VERSION"
          echo "APP_NAME: $APP_NAME"
        env:
          DART_VERSION: ${{ secrets.DART_VERSION }}
          APP_NAME: ${{ vars.APP_NAME }}
         
      
 
 
  