name: Test and Deploy the app

on: 
  workflow_dispatch:
  push: 
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      
      - name: "Print the key"
        run:  |
          echo "DART_VERSION está definido? ${{ secrets.DART_VERSION != '' }}"
          echo "APP_NAME está definido? ${{ vars.APP_NAME != '' }}"
         
      
 
 
  