name: Test and Deploy the app

on: 
  workflow_dispatch:
  push: 
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: "Print the key"
        run:  |
          echo "Dart Version: ${{ secrets.DART_VERSION }}"
          echo "App Name: ${{ vars.APP_NAME }}"
         
      
 
 
  